apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-tariff-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-tariff
  template:
    metadata:
      labels:
        app: order-tariff
    spec:
      containers:
      - name: order-tariff-container
        image: sidra17/order-tariff-service:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order-tariff-service
spec:
  type: LoadBalancer
  selector:
    app: order-tariff
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080